name: Publish Development Snapshot

on:
  push:
    branches:
    - main

jobs:
  publish:
    if: github.repository == 'kgbier/network-logger-android'
    runs-on: ubuntu-latest
    environment: publish

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Publish SNAPSHOT
      run: ./gradlew tasks # publish
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
    
    - name: Cleanup secrets
      if: always()
      run: rm -rf ~/.gradle/gradle.properties
