name: Publish

on:
  release:
    types:
    - created # Temporary, for testing
    - released

jobs:
  publish:
    if: github.repository == 'kgbier/network-logger-android' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: publish

    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Rewrite release version for publishing
      run: ./scripts/rewrite-version.sh $GITHUB_REF

    - name: Setup Gradle and Publish
      uses: gradle/gradle-build-action@v2

    - name: Publish release
      run: ./gradlew tasks # publish
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.PGP_SIGNING_KEY }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.PGP_SIGNING_PASSWORD }}

    - name: Cleanup secrets
      if: always()
      run: rm -rf ~/.gradle/gradle.properties
