name: Publish Development Snapshot

on:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: publish

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle and Publish
      uses: gradle/gradle-build-action@v2
      with:
        arguments: tasks # publish
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
